Title =  "TheWinds"
LanguageCode = "zh-CN"
BaseUrl = "http://blog.aifast.net/"
# BaseUrl = "http://thewinds.cn/"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
PygmentsUseClasses = true
DefaultContentLanguage = "zh"

[Params]
  Introduce = "TheWinds"
  Description = "风影的博客小站,CS,前端,Golang"
  Keywords =  "TheWinds,风影,博客,学习,计算机科学,记录,个人,思考,读书,笔记,技术,分享,Golang"
  Subtitle = "Build funny things"
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/avatar.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  #BaiduStatsId = "0b07433b4ab8d587dae7d34e71973839"
  # QQStatsId = "826201380"
  Fancybox = true

[Author]
  Name = "风影"

# [Params.Share]
#   #DuoShuo = ""
#   #Baidu = true

[Params.Disqus]
  ShortName= "thewinds"

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "技术"
  Pre = "code"
  URL = "/categories/技术/"
  Weight = 2
[[Menu.Main]]
  Name = "随笔"
  Pre = "tint"
  URL = "/categories/随笔/"
  Weight = 3

[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 6
[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/"
  Weight = 7

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/thewinds/"

[[Params.Socials]]
  Name = "Mail"
  Icon = "envelope"
  URL = "mailto:wind_ns@163.com"

# [[Params.Socials]]
#  Name = "知乎"
#   Icon = "globe"
#   URL = "https://www.zhihu.com/people/lan-ling-xin-yun"  
